data = [
    {
        "id": 0,
        "title": "Network Error",
        "price": "N/A",
        "description": "Unable to retrieve vehicle data due to network error.",
        "brand": "",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1200px-No-Image-Placeholder.svg.png"
    },
    {
        "id": 1,	
        "title": " Tata Nexon EV",
        "price": " Rs.14.49 - 17.19 Lakh",
        "description": " The Tata Nexon EV Prime has 1 Electric Engine on offer. It is available with the Automatic transmission. The Nexon EV Prime is a 5 seater and has length of 3993mm, width of 1811mm and a wheelbase of 2498mm.", 
        "brand": "TATA",
        "image": "https://imgd.aeplcdn.com/0x0/n/cw/ec/121341/nexon-ev-max-exterior-right-front-three-quarter-7.jpeg?isig=0",
        "battery_capacity": " 30.2 KWh",
        "max_power": " 127bhp",
        "max_torque": " 245Nm",
        "top_speed": "120 kmph",
        "seating_capacity": "5",
        "range": "312km",
        "boot_space": "350 LTR",
        "body_type": "SUV",
        "charging_time": "9.16 hours(a.c), 60 mins(d.c)",
        "dimensions": "Length (mm): 3993, Width (mm):1811,Height (mm):1606",                    
        "weight": " 1235 kg",
        "transmission type": "AUTOMATIC",
        "wheelbase": "2498mm",
        "ground_clearance": "205mm", 
    },
    {
        "id": 2,
        "title": "Hyundai Kona Electric",
        "price": "Rs 24 lakhs",
        "description": "Hyundai Kona is the first EV launched by Hyundai in India you can charge this electric vehicle from a wall socket in your home. It takes only 60 minutes to charge from 0% to 80% and around 6 hours to charge fully.",
        "brand":"Hyundai",
        "image": "https://s7d1.scene7.com/is/image/hyundai/2022-kona-ev-2?wid=1200&hei=630&qlt=85,0&fmt=webp",
        "battery_capacity": " 39.2KWh",
        "max_power": " 134bhp",
        "max_torque": " 395Nm",
        "top_speed" : "155.0 km/h",
        "seating_capacity": "5",
        "range": "452km",
        "boot_space": "332ltr",
        "body_type": "SUV",
        "charging_time": "6.16 hours(a.c), 57 mins(d.c)",
        "dimensions": "Length (mm): 4180, Width (mm):1800,Height (mm):1570",
        "weight": " 1420 kg",
        "transmission type": "AUTOMATIC",
        "wheelbase": "2600mm",
        "ground_clearance": "172mm", 
    },{
        "id": 3,
        "title": "MG ZS EV",
        "price": "Rs 22-24 lakhs",
        "description": "The MG ZS EV is a British-manufactured electric car launched in India this year. Features in this four-wheeler include a 10.1-inch touchscreen infotainment system, Android Auto and Apple CarPlay, and a panoramic sunroof, making it one of the best EV cars in India.",
        "brand": "MG",
        "image": "https://images.moneycontrol.com/static-mcnews/2020/01/MG-ZS-EV-e1579762015441.jpeg?impolicy=website&width=1600&height=900",
        "battery_capacity": "50.3 KWh",
        "max_power": "174.33 bhp",
        "max_torque": "280 Nm",
        "top_speed": "140 km/h",
        "seating_capacity": "5",
        "range": "461 km",
        "boot_space": "470 ltr",
        "body_type": "SUV",
        "charging_time": "9 hours (a.c), 60 mins (d.c)",
        "dimensions": "Length (mm): 4180, Width (mm): 1809, Height (mm): 1649",
        "weight": "1547 kg",
        "transmission_type": "Automatic",
        "wheelbase": "2585 mm",
        "ground_clearance": "177 mm"
    },{
        "id": 4,
        "title": "Mahindra e-Verito",
        "price": "9.13 lakhs to 9.46 lakhs",
        "description": "Mahindra e-Verito is a simple-looking sedan. It has a chrome front grille and centre cubic printed bezel and is available in two colours, namely, desat silver and diamond white.",
        "brand": "Mahindra",
        "image": "https://i0.wp.com/gomechanic.in/blog/wp-content/uploads/2020/04/Is-the-Mahindra-e-Verito-a-Viable-City-Commuter-01.jpg?fit=2401%2C1259&ssl=1",
        "battery_capacity": "288 Ah Lithium Ion",
        "max_power": "41.57 bhp @ 3500 rpm",
        "max_torque": "91 Nm @ 3000 rpm",
        "top_speed": "86 km/h",
        "seating_capacity": "5",
        "range": "110 km",
        "boot_space": "510 ltr",
        "body_type": "Sedan",
        "charging_time": "11 hours 30 min (100%) / Fast charging 1h30min (80%)",
        "dimensions": "Length (mm): 4247, Width (mm): 1740, Height (mm): 1540",
        "weight": "1265 kg",
        "transmission_type": "Automatic",
        "wheelbase": "2630 mm",
        "ground_clearance": "172 mm"
    },
    {
        "id": 5,
        "title": "Mahindra e-2oPlus",
        "price": "6.07 lakhs to 8.46 lakhs",
        "description": "The Mahindra e2oPlus has 3 Electric Engine on offer. It is available with the Automatic transmission. The e2oPlus is a 4 seater and has length of 3590mm, width of 1575mm and a wheelbase of 2258mm.",
        "brand": "Mahindra",
        "image": "https://stat.overdrive.in/wp-content/odgallery/2016/10/31805_Mahindra%20%20e2o_004.jpg",
        "battery_capacity": "210ah",
        "max_power": "25.4bhp",
        "max_torque": "70Nm",
        "top_speed": "80km/h",
        "seating_capacity": "4",
        "range": "110Km",
        "boot_space": "135ltr",
        "body_type": "Hatchback",
        "charging_time": "6hrs",
        "dimensions": "Length (mm): 3590, Width (mm): 1575, Height (mm): 1585",
        "weight": "932 kg",
        "transmission_type": "AUTOMATIC",
        "wheelbase": "2258mm",
        "ground_clearance": "170mm"
    },{
        "id": 6,
        "title": "Mini Cooper SE",
        "price": "52.50 lakhs",
        "description": "The Mini Cooper SE has one electric engine. It is available with Automatic Transmission. The Cooper is a 4-seater.",
        "brand": "Mini (Parent Brand: BMW)",
        "image": "https://images.hindustantimes.com/auto/img/2021/10/23/1600x900/mini-cooper-se-2020-im-test_1634988970538_1634988981134.jpg",
        "battery_capacity": "32.6 KwH",
        "max_power": "181 bhp",
        "max_torque": "270 Nm",
        "top_speed": "150 km/h",
        "seating_capacity": 4,
        "range": "270 Km",
        "boot space": "211 ltr",
        "body_type": "Hatchback",
        "charging_time": "36 min",
        "dimensions": "Length (mm): 3850, Width (mm): 1928, Height (mm): 1432",
        "weight": "1365 kg",
        "transmission_type": "AUTOMATIC",
        "wheelbase": "2495 mm",
        "ground_clearance": "N/A"
    },
    {
        "id": 7,
        "title": "TATA Tigor EV",
        "price": "12.49 lakhs to 13.75 lakhs",
        "description": "The TATA Tigor has one electric engine available with automatic transmission and it is a 5-seater.",
        "brand": "TATA",
        "image": "https://imgd.aeplcdn.com/1280x720/n/cw/ec/135723/tigor-ev-exterior-right-front-three-quarter.jpeg?isig=0&q=75",
        "battery_capacity": "26 Kwh",
        "max_power": "73.75bhp",
        "max_torque": "170Nm",
        "top_speed": "80km/h",
        "seating_capacity": "5",
        "range": "315Km",
        "boot_space": "316ltr",
        "body_type": "Sedan",
        "charging_time": "7.5hrs",
        "dimensions": "Length (mm): 3993, Width (mm): 1677, Height (mm): 1532",
        "weight": "1235 kg",
        "transmission_type": "AUTOMATIC",
        "wheelbase": "2450mm",
        "ground_clearance": "172mm"
    },
    {
        "id": 8,
        "title": "BYD E6",
        "price": "29.15 lakh",
        "description": "The BYD E6 has one electric engine available with automatic transmission and it is a 5-seater.",
        "brand": "BYD",
        "image": "https://val-byd.com.sg/wp-content/uploads/2021/08/e6-Exterior-White-1.png",
        "battery_capacity": "71.7Kwh",
        "max_power": "93.87bhp",
        "max_torque": "180Nm",
        "top_speed": "160km/h",
        "seating_capacity": "5",
        "range": "415Km",
        "boot_space": "580ltr",
        "body_type": "MUV",
        "charging_time": "12hrs",
        "dimensions": "Length (mm): 4695, Width (mm): 1810, Height (mm): 1670",
        "weight": "2380 kg",
        "transmission_type": "AUTOMATIC",
        "wheelbase": "2800mm",
        "ground_clearance": "170mm"
    },
    {
        "id": 9,
        "title": "Tiago EV",
        "price": "8.69 lakh to 12 lakhs",
        "description": "The TATA Tiago EV has one electric engine available with automatic transmission and it is a 5-seater.",
        "brand": "TATA",
        "image": "https://gumlet.assettype.com/evoindia%2F2022-09%2Fec234410-2655-4eb8-99e1-b5ffcfaaa325%2FTiago_EV_Charging.jpg?w=1200&auto=format%2Ccompress&ogImage=true&enlarge=true",
        "battery_capacity": "24KWh",
        "max_power": "73bhp",
        "max_torque": "114Nm",
        "top_speed": "120km/h",
        "seating_capacity": "5",
        "range": "315Km",
        "boot_space": "240ltr",
        "body_type": "Hatchback",
        "charging_time": "3.6hrs",
        "dimensions": "Length (mm): 3769, Width (mm): 1677, Height (mm): 1536",
        "weight": "1235 kg",
        "transmission_type": "AUTOMATIC",
        "wheelbase": "2400mm",
        "ground_clearance": "166mm"
    },
    {
        "id": 10,
        "title": "MG Coment EV",
        "price": "7.98 lakh",
        "description": "The MG Commet Ev has one electric engine available with automatic transmission and it is 4 seater.",
        "brand": "MG",
        "image": "https://imgd.aeplcdn.com/0x0/n/cw/ec/125193/comet-ev-exterior-right-front-three-quarter-2.jpeg?isig=0",
        "battery_capacity": "17.3Kwh",
        "max_power": "41.42bhp",
        "max_torque": "110Nm",
        "top_speed": "100km/h",
        "seating_capacity": "4",
        "range": "230 Km",
        "boot_space": "N/A",
        "body_type": "Hatchback",
        "charging_time": "7hrs",
        "dimensions": "Length (mm): 2974, Width (mm): 1505, Height (mm): 1640",
        "weight": "815 kg",
        "transmission_type": "AUTOMATIC",
        "wheelbase": "2010 mm",
        "ground_clearance": "N/A"
    },
    {
        "id": 11,
        "title": "Kia E6",
        "price": "60 lakh to 65 lakh",
        "description": "The Kia E6 has one electric engine available with automatic transmission and it is 5 seater.",
        "brand": "Kia",
        "image": "https://stat.overdrive.in/wp-content/uploads/2021/03/2021-Kia-EV6-front.jpg",
        "battery_capacity": "77Kwh",
        "max_power": "320 bhp",
        "max_torque": "605 Nm",
        "top_speed": "192 km/h",
        "seating_capacity": "5",
        "range": "708 Km",
        "boot_space": "520ltr",
        "body_type": "SUV",
        "charging_time": "6 hrs",
        "dimensions": "Length (mm): 4695, Width (mm): 1890,Height (mm): 1550",
        "weight": "2190 kg",
        "transmission_type": "AUTOMATIC",
        "wheelbase": "2900 mm",
        "ground_clearance": "178 mm"
    },
    {
        "id": 12,
        "title": "BMW iX",
        "price": "1.21 Crore",
        "description": "The BMW iX has one electric engine available with automatic transmission and it is 5 seater.",
        "brand": "BMW",
        "image": "https://cdni.autocarindia.com/ExtraImages/20220105021712_BMW_iX_M60_2022.jpg",
        "battery_capacity": "71Kwh",
        "max_power": "321 bhp",
        "max_torque": "630 Nm",
        "top_speed": "200 km/h",
        "seating_capacity": 5,
        "range": "425 Km",
        "boot_space": "500 ltr",
        "body_type": "SUV",
        "charging_time": "7.25 hrs",
        "dimensions": "Length (mm): 4953, Width (mm): 2230, Height (mm): 1695",
        "weight": "2285 kg",
        "transmission_type": "AUTOMATIC",
        "wheelbase": "3000mm",
        "ground_clearance": "202mm"
    },
    {
        "id": 13,
        "title": "BYD Atto 3",
        "price": "35 lakh",
        "description": "The BYD Atto 3 has one electric engine available with automatic transmission and it is a 5-seater.",
        "brand": "BYD",
        "image": "https://upload.wikimedia.org/wikipedia/commons/3/3e/BYD_Atto_3_1X7A6491.jpg",
        "battery_capacity": "60.48 Kwh",
        "max_power": "201 bhp",
        "max_torque": "310 Nm",
        "top_speed": "160 km/h",
        "seating_capacity": 5,
        "range": "521 Km",
        "boot_space": "440 ltr",
        "body_type": "SUV",
        "charging_time": "9.5 to 10 hrs",
        "dimensions": "Length (mm): 4455, Width (mm): 1875, Height (mm): 1615",
        "weight": "1750 kg",
        "transmission_type": "AUTOMATIC",
        "wheelbase": "2720 mm",
        "ground_clearance": "175mm"
    },  
    {
        "id": 14,
        "title": "Tesla Model S Long Range",
        "price": "Rs. 1.50 crore",
        "description": "The Tesla Model S Long Range has two electric engines available with automatic transmission and it is a 5-seater.",
        "brand": "Tesla",
        "image": "https://media.autoexpress.co.uk/image/private/s--X-WVjvBW--/f_auto,t_content-image-full-desktop@1/v1565798338/autoexpress/2019/08/01_7.jpg",
        "battery_capacity": "100 Kwh",
        "max_power": "670 bhp",
        "max_torque": "967 Nm",
        "top_speed": "250 km/h",
        "seating_capacity": 5,
        "range": "652 Km",
        "boot_space": "894 ltr",
        "body_type": "Sedan",
        "charging_time": "10-11 hrs",
        "dimensions": "Length (mm): 4988, Width (mm): 1964, Height (mm): 1445",
        "weight": "2100 kg",
        "transmission_type": "AUTOMATIC",
        "wheelbase": "2960 mm",
        "ground_clearance": "120mm"
    },
    {
        "id": 15,
        "title": "Tesla Model 3 Standard Range Plus",
        "price": "Rs. 46.00 lakh",
        "description": "The Tesla Model 3 Standard Range Plus has one electric engine available with automatic transmission and it is a 5-seater.",
        "brand": "Tesla",
        "image": "https://hips.hearstapps.com/hmg-prod/images/tesla-model-3-white-1565731697.jpg",
        "battery_capacity": "55 Kwh",
        "max_power": "283 bhp",
        "max_torque": "416 Nm",
        "top_speed": "225 km/h",
        "seating_capacity": 5,
        "range": "448 Km",
        "boot_space": "425 ltr",
        "body_type": "Sedan",
        "charging_time": "7-8 hrs",
        "dimensions": "Length (mm): 4694, Width (mm): 1933, Height (mm): 1443",
        "weight": "1680 kg",
        "transmission_type": "AUTOMATIC",
        "wheelbase": "2875 mm",
        "ground_clearance": "140mm"
    },
    {
        "id": 16,
        "title": "Tesla Model X Long Range",
        "price": "Rs. 2.20 crore",
        "description": "The Tesla Model X Long Range has two electric engines available with automatic transmission and it is a 7-seater.",
        "brand": "Tesla",
        "image": "https://platform.cstatic-images.com/xlarge/in/v2/stock_photos/681a042f-9795-4768-bbf3-84d76f80285e/6ad54efb-efc7-46c9-b132-22f508d43abe.png",
        "battery_capacity": "100 Kwh",
        "max_power": "670 bhp",
        "max_torque": "967 Nm",
        "top_speed": "250 km/h",
        "seating_capacity": 7,
        "range": "580 Km",
        "boot_space": "357 ltr",
        "body_type": "SUV",
        "charging_time": "10-11 hrs",
        "dimensions": "Length (mm): 5036, Width (mm): 2271, Height (mm): 1684",
        "weight": "2485 kg",
        "transmission_type": "AUTOMATIC",
        "wheelbase": "2965 mm",
        "ground_clearance": "137mm"
    }
]