data = [
    {
        "id": 0,
        "title": "Network Error",
        "price": "N/A",
        "description": "Unable to retrieve vehicle data due to network error.",
        "brand": "",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1200px-No-Image-Placeholder.svg.png"
    },
    {
        "id": 1,
        "title": "Tesla Model S",
        "price": "$69,420",
        "description": "The Tesla Model S is a luxury electric sedan that boasts impressive performance and range. With a range of up to 402 miles on a single charge, the Model S can accelerate from 0 to 60 mph in just 1.99 seconds thanks to its Ludicrous Mode. It also features a minimalist interior design, a large touchscreen display, and advanced autopilot capabilities.",
        "brand": "Tesla",
        "image": "https://ev-database.org/img/auto/Tesla_Model_S_2021/Tesla_Model_S_2021-01@2x.jpg",
        "battery_capacity": "100 kWh",
        "motor_power": "762 hp",
        "top_speed": "155 mph",
        "charging_time": "15 mins (Supercharger), 10 hours (Wall Connector)",
        "seating_capacity": "5",
        "dimensions": "196.0 x 77.3 x 56.9 in",
        "weight": "4,883 lb",
        "torque": "1,000 Nm",
        "drivetrain": "AWD",
        "wheelbase": "116.5 in",
        "ground_clearance": "4.6 in",
        "cargo_capacity": "28.4 cu ft"
    },
    {
        "id": 2,
        "title": "Chevrolet Bolt EV",
        "price": "$31,995",
        "description": "The Chevrolet Bolt EV is a practical and affordable electric hatchback with a range of up to 259 miles on a single charge. It features a spacious interior, responsive handling, and quick acceleration. It also has a long list of standard features, including a 10.2-inch touchscreen display, Apple CarPlay and Android Auto, and a suite of advanced safety features.",
        "brand": "Chevrolet",
        "image": "https://hips.hearstapps.com/hmg-prod/images/2019-chevrolet-boltev-016-1556560004.jpg",
        "battery_capacity": "66 kWh",
        "motor_power": "200 hp",
        "top_speed": "93 mph",
        "charging_time": "30 mins (DC fast charger), 9.5 hours (240V home charger)",
        "seating_capacity": "5",
        "dimensions": "164.0 x 69.5 x 62.8 in",
        "weight": "3,580 lb",
        "torque": "266 lb-ft",
        "drivetrain": "FWD",
        "wheelbase": "102.4 in",
        "ground_clearance": "6.4 in",
        "cargo_capacity": "16.6 cu ft"
    },{
        "id": 3,
        "title": "Porsche Taycan",
        "price": "$81,250",
        "description": "The Porsche Taycan is a luxury electric sedan that combines breathtaking performance with elegant styling. With a range of up to 227 miles on a single charge, the Taycan can accelerate from 0 to 60 mph in as little as 2.4 seconds thanks to its electric motors that produce up to 616 horsepower. The Taycan also features a sleek and modern interior, a user-friendly infotainment system, and advanced safety features.",
        "brand": "Porsche",
        "image": "https://www.porsche.com/microsite/mission-e/assets/images/model-overview/911-turbo-1.jpg",
        "battery_capacity": "93.4 kWh",
        "motor_power": "616 hp",
        "top_speed": "162 mph",
        "charging_time": "22.5 mins (DC fast charger), 9 hours (240V home charger)",
        "seating_capacity": "4",
        "dimensions": "195.4 x 77.4 x 54.3 in",
        "weight": "4,960 lb",
        "torque": "774 lb-ft",
        "drivetrain": "AWD",
        "wheelbase": "114.2 in",
        "ground_clearance": "5.0 in",
        "cargo_capacity": "17.0 cu ft"
    },{
        "id": 4,
        "title": "Tesla Model S",
        "price": "$79,990",
        "description": "The Tesla Model S is a luxury electric sedan that offers impressive range and performance. It can travel up to 412 miles on a single charge and can accelerate from 0 to 60 mph in just 2.4 seconds in its top-of-the-line Plaid trim. The Model S also features a spacious and luxurious interior, a large touchscreen infotainment system, and advanced driver assistance features.",
        "brand": "Tesla",
        "image": "https://www.tesla.com/sites/default/files/modelsx-new/social/model-s-hero-social.jpg",
        "battery_capacity": "up to 100 kWh",
        "motor_power": "up to 1,020 hp",
        "top_speed": "200 mph",
        "charging_time": "15 mins (Supercharger V3), 11 hours (240V home charger)",
        "seating_capacity": "5-7",
        "dimensions": "196 x 77 x 56 in",
        "weight": "4,883-5,531 lb",
        "torque": "up to 1,050 lb-ft",
        "drivetrain": "AWD",
        "wheelbase": "116.5 in",
        "ground_clearance": "4.6 in",
        "cargo_capacity": "28.0 cu ft"
    },
    {
        "id": 5,
        "title": "Chevrolet Bolt EV",
        "price": "$31,995",
        "description": "The Chevrolet Bolt EV is a practical and affordable electric car that offers a range of up to 259 miles on a single charge. It has a spacious and comfortable interior, a user-friendly infotainment system, and good safety ratings. The Bolt EV is also available with a long list of advanced driver assistance features.",
        "brand": "Chevrolet",
        "image": "https://www.chevrolet.com/content/dam/chevrolet/na/us/english/index/vehicles/2022/electric/bolt-ev/carousel/02-images/2022-chevrolet-bolt-ev-lt-carousel-01.jpg",
        "battery_capacity": "66 kWh",
        "motor_power": "200 hp",
        "top_speed": "93 mph",
        "charging_time": "30 mins (DC fast charger), 9.5 hours (240V home charger)",
        "seating_capacity": "5",
        "dimensions": "164 x 69 x 63 in",
        "weight": "3,580 lb",
        "torque": "266 lb-ft",
        "drivetrain": "FWD",
        "wheelbase": "102.4 in",
        "ground_clearance": "6.0 in",
        "cargo_capacity": "16.6 cu ft"
    },{
        "id": 6,
        "title": "Audi e-tron",
        "price": "$65,900",
        "description": "The Audi e-tron is a luxurious and spacious electric SUV that offers a range of up to 222 miles on a single charge. It has a comfortable and high-tech interior, a smooth and quiet ride, and good safety ratings. The e-tron also features an advanced regenerative braking system that can recover up to 30% of the car's energy during deceleration.",
        "brand": "Audi",
        "image": "https://www.audiusa.com/content/dam/audiusa/myaudi/vehicle-manuals/e-tron/2022/Owners-Manual-ETRON22-MY22-EN.pdf",
        "battery_capacity": "95 kWh",
        "motor_power": "355 hp",
        "top_speed": "124 mph",
        "charging_time": "30 mins (DC fast charger), 8.5 hours (240V home charger)",
        "seating_capacity": "5",
        "dimensions": "193 x 76 x 65 in",
        "weight": "5,756 lb",
        "torque": "414 lb-ft",
        "drivetrain": "AWD",
        "wheelbase": "115.3 in",
        "ground_clearance": "6.9 in",
        "cargo_capacity": "28.5 cu ft"
    },
    {
        "id": 7,
        "title": "Porsche Taycan",
        "price": "$81,250",
        "description": "The Porsche Taycan is a high-performance electric car that offers a range of up to 227 miles on a single charge. It has a sleek and sporty exterior, a luxurious and driver-focused interior, and impressive acceleration and handling. The Taycan also features a fast and reliable charging system that can add up to 62 miles of range in just 5 minutes with a high-power DC fast charger.",
        "brand": "Porsche",
        "image": "https://www.porsche.com/microsite/taycan/USA.aspx",
        "battery_capacity": "up to 93.4 kWh",
        "motor_power": "402-750 hp",
        "top_speed": "161-260 mph",
        "charging_time": "22.5 mins (DC fast charger), 9 hours (240V home charger)",
        "seating_capacity": "4-5",
        "dimensions": "195 x 77 x 55 in",
        "weight": "4,566-5,132 lb",
        "torque": "263-774 lb-ft",
        "drivetrain": "AWD",
        "wheelbase": "114.2 in",
        "ground_clearance": "4.7 in",
        "cargo_capacity": "12.9 cu ft"
    },
]